### ISSUE TITLE
Levy_fit error II

### ISSUE THREAD

**Issue by rodrigomp84** [josemiotto/pylevy#7]
First of all, thank you for the great job. 
I'm new to python, so I apologize if this is just me being stupid. Also if the project is no longer under development.

Anyway, I'm facing problems with the Levy_fit function and the other open issue #3 on this topic did not help (I noted some things were already corrected in the code). It seems quite similar though, and I suspect it has to do with Python versions, but this is all still a mystery to me. I've been trying to use python3, and I also tested 2.7 with no luck.

If I simply use
`param = levy.fit_levy(data)`
the code works and gives results which seem fine, although my data set is quite weird. It gives me beta=-1 when I would expect 0, still I would bet that's on the data.
But if I try to fix beta
`param = levy.fit_levy(data, beta=0.0)`
then I get the error message

> Traceback (most recent call last):
  File "save_epsilons_alpha2.py", line 29, in <module>
    param=levy.fit_levy(v[i:i+M],beta=0.0)
  File "/usr/local/lib/python3.4/dist-packages/levy.py", line 354, in fit_levy
    parameters.x = optimize.minimize(neglog_density, parameters.x, method='L-BFGS-B', bounds=par_bounds)
  File "/usr/local/lib/python3.4/dist-packages/scipy/optimize/_minimize.py", line 450, in minimize
    callback=callback, **options)
  File "/usr/local/lib/python3.4/dist-packages/scipy/optimize/lbfgsb.py", line 260, in _minimize_lbfgsb
    raise ValueError('length of x0 != length of bounds')
ValueError: length of x0 != length of bounds

Since I have this weird data I also tried fixing beta=-1 but I get the same message. Same thing if trying to fix mu. Where am I screwing this?

**Comment by josemiotto** [comment]
Hi Rodrigo,

it's a long time that I do not work in that code. Maybe this weekend is
time to fix those bugs! so, I'll let you know, but don't have many hopes :)

best
José
